### ISSUE TITLE
private_network vagrant up error (undefined method `read_host_only_networks')

### ISSUE THREAD

**Issue by upszot** [hashicorp/vagrant#13655]
### Debug output
[>Vagrant up --debug  (full log)](https://gist.github.com/upszot/4c0d4932c1180b81ecd0bd7b02206c45)

The following is a portion of the vagrant up output:

```vagrant  up
Bringing machine 'default' up with 'virtualbox' provider...
==> default: Cloning VM...
==> default: Matching MAC address for NAT networking...
==> default: Checking if box 'ubuntu/jammy64' version '20231027.0.0' is up to date...
==> default: Setting the name of the VM: VMPruebas
==> default: Clearing any previously set network interfaces...
==> default: Destroying VM and associated drives...
/opt/vagrant/embedded/gems/gems/vagrant-2.4.5/plugins/providers/virtualbox/action/network.rb:362:in `hostonly_config': undefined method `read_host_only_networks' for an instance of VagrantPlugins::ProviderVirtualBox::Driver::Meta (NoMethodError)

            hostif = @env[:machine].provider.driver.read_host_only_networks.detect { |interface|
                                                   ^^^^^^^^^^^^^^^^^^^^^^^^
Did you mean?  read_host_only_interfaces
	from /opt/vagrant/embedded/gems/gems/vagrant-2.4.5/plugins/providers/virtualbox/action/network.rb:119:in `block in call'
 ```

### Expected behavior

Vagrant should have been able to bring up the Ubuntu virtual machine using VirtualBox without requiring the explicit specification of `virtualbox__intnet: true` in the private network configuration. In previous versions of Vagrant and VirtualBox, configuring a private network worked correctly without this additional option, creating a functional host-only network for communication between the host and the guest machine.

### Actual behavior

When running `vagrant up` with a standard private network configuration (for example, `config.vm.network "private_network", ip: "192.168.56.2"`), an error occurred that prevented the virtual machine from being brought up. The specific error was: `NoMethodError: undefined method 'read_host_only_networks' for an instance of VagrantPlugins::ProviderVirtualBox::Driver::Meta`. This suggests that Vagrant was unable to interact correctly with the VirtualBox host-only network configuration in the way it did previously. The workaround found was to add the `virtualbox__intnet: true` option to the private network configuration in the `Vagrantfile`.

#### Version History (Working vs. Issues)

**Worked correctly with:**

* Vagrant: 2.4.3-1.x86_64
* VirtualBox: 7.0-7.0.24_167081_fedora40-1.x86_64

**Issues were experienced with the following combinations:**

* Vagrant: 2.4.4-1.x86_64
    VirtualBox: 7.0-7.0.26_168464_fedora40-1.x86_64

* Vagrant: 2.4.5-1.x86_64
    VirtualBox: 7.0-7.0.26_168464_fedora40-1.x86_64

* Vagrant: 2.4.5-1.x86_64
    VirtualBox: 7.1-7.1.8_168469_fedora40-1.x86_64

**Note:** This issue was also reproduced on another machine running Windows 11, using VirtualBox 7.0 + Vagrant 2.4.4 and VirtualBox 7.1 + Vagrant 2.4.5, yielding the same error.

#### Host operating system
Fedora 40

#### Guest operating system

Ubuntu 22.04 LTS (the box used is 'ubuntu/jammy64')

#### Steps to reproduce

1. Create a Vagrantfile with the following minimal configuration:
   (Note: The IP address may vary, the important part is the basic private network configuration without virtualbox__intnet: true).

3. Run the command vagrant up in the directory where the Vagrantfile was saved
4. Observe the error NoMethodError: undefined method 'read_host_only_networks'
#### Vagrantfile

```ruby
Vagrant.configure("2") do |config|
  config.vm.box = "ubuntu/jammy64"
  config.vm.network "private_network", ip: "192.168.56.2"
  config.vm.provider "virtualbox" do |vb|
    vb.name = "test-vm"
  end
end
```

Workaround / Temporary Solution (Undesired)
As a temporary workaround to avoid this error, the private network configuration in the Vagrantfile can be modified by adding the virtualbox__intnet: true option. This forces Vagrant to configure the private network as an internal network in VirtualBox, which prevents the read_host_only_networks error.

Example of Vagrantfile with the workaround:

```ruby
Vagrant.configure("2") do |config|
  config.vm.box = "ubuntu/jammy64"
  config.vm.network "private_network", ip: "192.168.56.2", virtualbox__intnet: true
  config.vm.provider "virtualbox" do |vb|
    vb.name = "test-vm-fixed"
  end
end
```

While this modification resolves the error and allows the virtual machine to be brought up, it is considered a workaround because the private network configuration should function without explicitly specifying the internal network type in VirtualBox.

**Comment by loop-evgeny** [comment]
Seems like this was broken by #13644. Downgrading to 2.4.3 makes Vagrant work again, but I hope this gets fixed ASAP, as I suspect we're not the only 2 users affected.
