### ISSUE TITLE
Error with librarian_puppet after upgrading to 1.5.1 (and also upgrading VirtualBox)

### ISSUE THREAD

**Issue by bobeagan** [hashicorp/vagrant#3352]
Recently updated to 1.5.1 from 1.4.x and receiving the following error in the console after attempting a `vagrant up`:

```
/Users/me/.vagrant.d/gems/gems/vagrant-librarian-puppet-0.3.1/lib/vagrant-librarian-puppet/action/librarian_puppet.rb:12:in `initialize': undefined method `librarian_puppet' for nil:NilClass (NoMethodError)
```

VirtualBox 4.3.10 r93012
Mac OS X 10.9.2

Seems strange to be failing with librarian_puppet when that instance uses chef.  I had upgraded VirtualBox at the same time and tried to reboot computer after getting this error at first, but still happening.  

Any help tracking down a solution is appreciated.
