### ISSUE TITLE
error with librarian after upgrade to 1.3.3

### ISSUE THREAD

**Issue by arosenhagen** [hashicorp/vagrant#2231]
After upgrading from 1.3.2 to 1.3.3 I got this error when using the vagrant-librarian-chef plugin. Host is OSX 10.8.2

```
/.vagrant/gems/gems/librarian-0.1.1/lib/librarian/posix.rb:107:in `run!': dyld: lazy symbol binding failed: Symbol not found: _iconv_open (Librarian::Posix::CommandFailure)
  Referenced from: /usr/bin/git
  Expected in: /Applications/Vagrant/bin/../embedded/lib/libiconv.2.dylib

dyld: Symbol not found: _iconv_open
  Referenced from: /usr/bin/git
  Expected in: /Applications/Vagrant/bin/../embedded/lib/libiconv.2.dylib
```
