### ISSUE TITLE
OSX Guests not working in 1.5

### ISSUE THREAD

**Issue by sethvargo** [hashicorp/vagrant#3143]
It looks like something in the networking plugin broke in the latest version of vagrant.

``` text
/Applications/Vagrant/embedded/gems/gems/vagrant-1.5.0.dev/plugins/guests/darwin/cap/configure_networks.rb:21:in `configure_networks': undefined method `read' for Vagrant::Util::IO:Class (NoMethodError)
```

Full gist output for your viewing pleasure: https://gist.github.com/sethvargo/efdc2f824d447f9b2558
