### PR TITLE
Split out cygwin path and ensure bin exists

### LINKED ISSUE #8954: vagrant 2.0: rsync does not work in Win10 + cygwin anymore
### Vagrant version
$ vagrant.exe --version
Vagrant 2.0.0

### Host operating system
Windows 10 + Cygwin64

### Guest operating system
Ubuntu 16.04

### Vagrantfile
```ruby
# -*- mode: ruby -*-
# vi: set ft=ruby :

# Vagrantfile API/syntax version. Don't touch unless you know what you're doing!
VAGRANTFILE_API_VERSION = "2"



Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|
  config.vm.box = "ubuntu/xenial64"
  config.vm.provision :shell, path: "vagrant-bootstrap/vagrant-bootstrap.sh"
  config.vm.provision :shell, path: "vagrant-bootstrap/vagrant-bootstrap-user.sh", privileged: false
  config.vm.hostname = "vagrant-test"
  config.vm.provider "virtualbox" do |v|
    v.memory = 2048
    v.customize ["modifyvm", :id, "--natdnshostresolver1", "on"]
    v.customize ["modifyvm", :id, "--natdnsproxy1", "on"]
  end
  config.vm.synced_folder ".", "/vagrant",
    type: "rsync",
    rsync__exclude: [
      ".vagrant/",
      ".git/"
    ],
    owner: "ubuntu", group: "ubuntu"
end
```

### Expected behavior
Files should be synced to guest OS as it worked in vagrant 1.9.x

### Actual behavior
```
[...]
==> default: Setting hostname...
==> default: Rsyncing folder: /home/user/Workspace/vagrant-test/ => /vagrant
==> default:   - Exclude: [".vagrant/", ".git/"]
There was an error when attempting to rsync a synced folder.
Please inspect the error message below for more info.

Host path: /home/user/Workspace/vagrant-test/
Guest path: /vagrant
Command: "rsync" "--verbose" "--archive" "--delete" "-z" "--copy-links" "--chmod=ugo=rwX" "--no-perms" "--no-owner" "--no-group" "--rsync-path" "sudo rsync" "-e" "ssh -p 2200 -o LogLevel=FATAL   -o IdentitiesOnly=yes -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null -i 'D:/cygwin64/home/user/Workspace/vagrant-test/.vagrant/machines/default/virtualbox/private_key'" "--exclude" ".vagrant/" "--exclude" ".git/" "/home/user/Workspace/vagrant-test/" "ubuntu@127.0.0.1:/vagrant"
Error: This rsync lacks old-style --compress due to its external zlib.  Try -zz.
Continuing without compression.

rsync: change_dir "/home/user/Workspace/vagrant-test" failed: No such file or directory (2)
rsync error: some files/attrs were not transferred (see previous errors) (code 23) at main.c(1196) [sender=3.1.2]
```

### Steps to reproduce
1. Open cygwin
2. cd to project path
3. Run ```vagrant up``` / ```vagrant rsync-auto```

### LINKED ISSUE #8960: undefined method `gsub!' for nil:NilClass (NoMethodError)
Please note that the Vagrant issue tracker is reserved for bug reports and
enhancements. For general usage questions, please use the Vagrant mailing list:
https://groups.google.com/forum/#!forum/vagrant-up. Thank you!

### Vagrant version
Fresh install Vagrant 2.0.0 

### Host operating system
Windows 10 64 latest

### Guest operating system
Ubuntu 16.04 pretty sure

### Vagrantfile

```ruby
# -*- mode: ruby -*-
# vi: set ft=ruby :

require 'json'
require 'yaml'

VAGRANTFILE_API_VERSION ||= "2"
confDir = $confDir ||= File.expand_path("vendor/laravel/homestead", File.dirname(__FILE__))

homesteadYamlPath = "Homestead.yaml"
homesteadJsonPath = "Homestead.json"
afterScriptPath = "after.sh"
aliasesPath = "aliases"

require File.expand_path(confDir + '/scripts/homestead.rb')

Vagrant.require_version '>= 1.9.0'

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|
    if File.exist? aliasesPath then
        config.vm.provision "file", source: aliasesPath, destination: "/tmp/bash_aliases"
        config.vm.provision "shell" do |s|
            s.inline = "awk '{ sub(\"\r$\", \"\"); print }' /tmp/bash_aliases > /home/vagrant/.bash_aliases"
        end
    end

    if File.exist? homesteadYamlPath then
        settings = YAML::load(File.read(homesteadYamlPath))
    elsif File.exist? homesteadJsonPath then
        settings = JSON.parse(File.read(homesteadJsonPath))
    else
        abort "Homestead settings file not found in #{confDir}"
    end

    Homestead.configure(config, settings)

    if File.exist? afterScriptPath then
        config.vm.provision "shell", path: afterScriptPath, privileged: false
    end

    if defined? VagrantPlugins::HostsUpdater
        config.hostsupdater.aliases = settings['sites'].map { |site| site['map'] }
    end
end
```

Please note, if you are using Homestead or a different Vagrantfile format, we
may be unable to assist with your issue. Try to reproduce the issue using a
vanilla Vagrantfile first.

### Debug output
https://gist.github.com/narration-sd/cd8a7c2a2f7c11d8de404f055c622641

### Expected behavior
Vagrant should bring up my site

### Actual behavior
Stack trace

### Steps to reproduce
1. install 2.0.0 over 1.9.6
2. vagrant up
3.

### References
Are there any other GitHub issues (open or closed) that should be linked here?
For example:

### PR DESCRIPTION
**Pull request by briancain**
This commit splits out the msys2 and cygwin path functions for
expanding a path with the cygpath tool. It also ensures that the tool
itself exists when the Which class is called so that it doesn't attempt
to escape slashes on nil.

Fixes #8960

### CODE REVIEW

**Comment by narration-sd** [comment]
Sounds good -- looking  forward to trying it.

Thanks, @briancain

**Comment by briancain** [comment]
Hey @narration-sd - just an fyi, this PR will mostly be focusing on fixing #8954 . The issue you reported will be fixed in a vagrant-installers PR just to ensure we are detecting cygwin properly.

**Comment by avoidik** [comment]
My apologies, this PR has been merged but not released and affects a lot of people on Windows. Any plans to put it in release section?

**Comment by avoidik** [comment]
https://github.com/hashicorp/vagrant/milestone/27

**Comment by briancain** [comment]
@avoidik - were working on getting the next release out as we speak. This will be included for that! If you look at the upstream issue this PR fixes #8954, you'll see that it's included in the 2.0.1 milestone. Thanks!
