### ISSUE TITLE
Can't install plugin vagrant-parallels in 2.4.3 (Failed to build gem native extension)

### ISSUE THREAD

**Issue by mikescott** [hashicorp/vagrant#13548]
`vagrant plugin install vagrant-parallels` results in an error "Failed to build gem native extension".

### Expected behavior

Plugin should install successfully.

This works in 2.4.1.

Doesn't work in 2.4.2 because of a different issue (#13527)

### Actual behavior

```
vagrant plugin install vagrant-parallels
Installing the 'vagrant-parallels' plugin. This can take a few minutes...
Building native extensions. This could take a while...
Vagrant failed to properly resolve required dependencies. These
errors can commonly be caused by misconfigured plugin installations
or transient network issues. The reported error is:

ERROR: Failed to build gem native extension.

    current directory: /Users/mike/.vagrant.d/gems/3.3.6/gems/racc-1.8.1/ext/racc/cparse
/opt/vagrant/embedded/bin/ruby extconf.rb
creating Makefile

current directory: /Users/mike/.vagrant.d/gems/3.3.6/gems/racc-1.8.1/ext/racc/cparse
make DESTDIR\= sitearchdir\=./.gem.20241128-75255-pjhs96 sitelibdir\=./.gem.20241128-75255-pjhs96 clean

current directory: /Users/mike/.vagrant.d/gems/3.3.6/gems/racc-1.8.1/ext/racc/cparse
make DESTDIR\= sitearchdir\=./.gem.20241128-75255-pjhs96 sitelibdir\=./.gem.20241128-75255-pjhs96
compiling cparse.c
clang: warning: no such sysroot directory: '/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk' [-Wmissing-sysroot]
In file included from cparse.c:12:
In file included from /opt/vagrant/embedded/include/ruby.h:38:
In file included from /opt/vagrant/embedded/include/ruby/ruby.h:25:
/opt/vagrant/embedded/include/ruby/defines.h:16:10: fatal error: 'stdio.h' file not found
   16 | #include <stdio.h>
      |          ^~~~~~~~~
1 error generated.
make: *** [cparse.o] Error 1

make failed, exit code 2

Gem files will remain installed in /Users/mike/.vagrant.d/gems/3.3.6/gems/racc-1.8.1 for inspection.
Results logged to /Users/mike/.vagrant.d/gems/3.3.6/extensions/arm64-darwin/3.3.0/racc-1.8.1/gem_make.out
```

#### Vagrant version

Vagrant 2.4.3

#### Host operating system

macOS Sonoma (14.7.1) on Apple Silicon

#### Steps to reproduce

1. Install Vagrant 2.4.3
2. Run `vagrant plugin install vagrant-parallels`

**Comment by mikescott** [comment]
The plugin installs correctly when the Xcode command line developer tools are installed, but this wasn't a requirement in previous versions of Vagrant

**Comment by chrisroberts** [comment]
Closing as this was just an issue of missing development tools. 

Note on the error for the specific plugin being installed: it looks like the plugin likely changed its dependencies (or the dependency itself changed and added an extension). The `racc` gem is what requires the development tools for building the extension.
