### ISSUE TITLE
Vagrant 1.4.3 having issues with string concatenation

### ISSUE THREAD

**Issue by jlk** [hashicorp/vagrant#2859]
Just upgraded to 1.4.3 - When I tried to use an existing Vagrantfile that worked in 1.4.2, I get the following:

<pre>
$ vagrant status
/Users/jlk/code/vagrants/dev/Vagrantfile:13:in `block (2 levels) in <top (required)>': undefined method `+' for nil:NilClass (NoMethodError)
</pre>

Vagrantfile is below. The "undefined method" mentioned above is my attempting to concatenate 2 strings, which used to work...

<pre>
VAGRANTFILE_API_VERSION = "2"

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|
  config.vm.box = "centos64_minimal"
  config.vm.box_url = "http://developer.nrel.gov/downloads/vagrant-boxes/CentOS-6.4-x86_64-v20130731.box"

  config.vm.hostname = "log01"
  config.vm.network "forwarded_port", guest: 9292, host: 9292
  config.vm.network "forwarded_port", guest: 9200, host: 9200
  config.vm.network "forwarded_port", guest: 8080, host: 8000

  config.vm.provision "puppet" do |puppet|
    puppet.manifests_path = ENV['PUPPET_ENVIRONMENTS'] + "/environments/production"
    puppet.manifest_file  = "site.pp"

    puppet.facter = {
      "vagrant" => "1"
    }
  end
end
</pre>
