### ISSUE TITLE
Vagrant does not work on Mac OS 10.9.5 since version 2.2.7

### ISSUE THREAD

**Issue by smarthouseprojectdotorg** [hashicorp/vagrant#11661]
Vagrant 2.2.7+ fails on Mac OS 10.9.5 with the following error: 

```
dyld: Symbol not found: _fdopendir$INODE64
  Referenced from: /usr/local/bin/vagrant
  Expected in: flat namespace

```

I can't and won't upgrade OS for an intentional reason. Can the above be fixed please? Probably by linking Vagrant statically?

**Comment by chrisroberts** [comment]
Hi there. The latest release of Vagrant was packaged using 10.9 as the target. Please try installing 2.2.9 and see if it resolves your issue. We do our best to support older versions of operating systems (and work was done for the last release to support older macOS versions) but we cannot guarantee that packages will work on operating systems which have reached end of life.

Cheers!
