### ISSUE TITLE
Error: with vagrant up and vagrant add OSX 10.9.3

### ISSUE THREAD

**Issue by ghost** [hashicorp/vagrant#3972]
Vagrant 1.6.3 and Vagrant 1.6.2
VBoxManage 4.3.10r93012

I was trying to create a vagrant instance from a prebaked Vagrantfile

``` ruby
  config.vm.box = "opscode-ubuntu-12.04"
  config.vm.box_url = "https://opscode-vm.s3.amazonaws.com/vagrant/opscode_ubuntu-12.04_chef-11.2.0.box"
```

``` text
vagrant up

==> default: Adding box 'opscode-ubuntu-12.04' (v0) for provider: virtualbox
 INFO box_collection: Box not found: opscode-ubuntu-12.04 (virtualbox)
 INFO box_add: Downloading box: https://opscode-vm.s3.amazonaws.com/vagrant/opscode_ubuntu-12.04_chef-11.2.0.box => /Users/212396312/.vagrant.d/tmp/box75f5d5af618e0d0398133a7e7143ef525f15572a
 INFO interface: detail: Downloading: https://opscode-vm.s3.amazonaws.com/vagrant/opscode_ubuntu-12.04_chef-11.2.0.box
 INFO interface: detail:     default: Downloading: https://opscode-vm.s3.amazonaws.com/vagrant/opscode_ubuntu-12.04_chef-11.2.0.box
    default: Downloading: https://opscode-vm.s3.amazonaws.com/vagrant/opscode_ubuntu-12.04_chef-11.2.0.box
 INFO downloader: Downloader starting download: 
 INFO downloader:   -- Source: https://opscode-vm.s3.amazonaws.com/vagrant/opscode_ubuntu-12.04_chef-11.2.0.box
 INFO downloader:   -- Destination: /Users/212396312/.vagrant.d/tmp/box75f5d5af618e0d0398133a7e7143ef525f15572a
 INFO subprocess: Starting process: ["/Applications/Vagrant/bin/../embedded/bin/curl", "--fail", "--location", "--max-redirs", "10", "--user-agent", "Vagrant/1.6.2", "--continue-at", "-", "--output", "/Users/212396312/.vagrant.d/tmp/box75f5d5af618e0d0398133a7e7143ef525f15572a", "https://opscode-vm.s3.amazonaws.com/vagrant/opscode_ubuntu-12.04_chef-11.2.0.box"]
 INFO subprocess: Command in the installer. Specifying DYLD_LIBRARY_PATH...
DEBUG subprocess: Selecting on IO
DEBUG subprocess: stderr: dyld: Symbol not found: _iconv
  Referenced from: /usr/lib/libcups.2.dylib
  Expected in: /applications/vagrant/bin/../embedded/lib/libiconv.2.dylib
 in /usr/lib/libcups.2.dylib
DEBUG subprocess: Waiting for process to exit. Remaining to timeout: 31999
DEBUG subprocess: Exit status: 5
 WARN downloader: Downloader exit code: 5
```

Thinking that I had done something wrong I manually downloaded the box and tried t oadd it manually 

``` text
vagrant box add opscode-ubuntu-12.04 ~/Downloads/opscode_ubuntu-12.04_chef-11.2.0.box

=> box: Adding box 'opscode-ubuntu-12.04' (v0) for provider: 
 INFO box_add: Downloading box: file:///Users/212396312/Downloads/opscode_ubuntu-12.04_chef-11.2.0.box => /Users/212396312/.vagrant.d/tmp/boxc7eb6deec7e9d1c839ca036140f2b5cb144d03e0
 INFO interface: detail: Downloading: file:///Users/212396312/Downloads/opscode_ubuntu-12.04_chef-11.2.0.box
 INFO interface: detail:     box: Downloading: file:///Users/212396312/Downloads/opscode_ubuntu-12.04_chef-11.2.0.box
    box: Downloading: file:///Users/212396312/Downloads/opscode_ubuntu-12.04_chef-11.2.0.box
 INFO downloader: Downloader starting download: 
 INFO downloader:   -- Source: file:///Users/212396312/Downloads/opscode_ubuntu-12.04_chef-11.2.0.box
 INFO downloader:   -- Destination: /Users/212396312/.vagrant.d/tmp/boxc7eb6deec7e9d1c839ca036140f2b5cb144d03e0
 INFO subprocess: Starting process: ["/Applications/Vagrant/bin/../embedded/bin/curl", "--fail", "--location", "--max-redirs", "10", "--user-agent", "Vagrant/1.6.2", "--continue-at", "-", "--output", "/Users/212396312/.vagrant.d/tmp/boxc7eb6deec7e9d1c839ca036140f2b5cb144d03e0", "file:///Users/212396312/Downloads/opscode_ubuntu-12.04_chef-11.2.0.box"]
 INFO subprocess: Command in the installer. Specifying DYLD_LIBRARY_PATH...
DEBUG subprocess: Selecting on IO
DEBUG subprocess: stderr: dyld: Symbol not found: _iconv
  Referenced from: /usr/lib/libcups.2.dylib
  Expected in: /applications/vagrant/bin/../embedded/lib/libiconv.2.dylib
 in /usr/lib/libcups.2.dylib
DEBUG subprocess: Waiting for process to exit. Remaining to timeout: 32000
DEBUG subprocess: Exit status: 5
 WARN downloader: Downloader exit code: 5
```

To very similar result.  I had it working with vagrant 1.6.2 on another workstation.

Only major difference between the workstations would have been an Apple security patch from 6/2/14
